type: spec.openrewrite.org/v1beta/recipe
name: com.img.spring_rewrite_demo.config.NewRecipe
displayName: 'Hello rewrite'
description: 'Description.'
tags:
  - spring
  - boot
recipeList:
  - org.openrewrite.java.ChangeMethodName:
      methodPattern: "com.imag.spring_rewrite_demo.TestClass demo"
      newMethodName: "demoTest"
